export const accessibilityWords = [
    { word: "ALERT", fact: "An alert notifies users of important information in an accessible way" },
    { word: "LABEL", fact: "Labels help users understand the purpose of form controls and other UI elements" },
    { word: "FOCUS", fact: "The focus state ensures keyboard and screen reader users know where they are" },
    { word: "COLOR", fact: "Ensuring sufficient color contrast is vital for users with visual impairments" },
    { word: "AUDIO", fact: "Audio accessibility includes captions for hearing-impaired users" },
    { word: "MEDIA", fact: "Accessible media provides captions, transcripts, and audio descriptions" },
    { word: "LINKS", fact: "Descriptive links help users understand the purpose of each link" },
    { word: "INPUT", fact: "Accessible input fields have clear labels and instructions" },
    { word: "TEXTS", fact: "Text alternatives provide meaning to images for screen readers" },
    { word: "ZOOMS", fact: "Zoom functionality is essential for users with visual impairments" },
    { word: "ORDER", fact: "Tab order ensures logical navigation for keyboard users" },
    { word: "FORMS", fact: "Accessible forms use labels, instructions, and error messages effectively" },
    { word: "GUIDE", fact: "Guided navigation helps users with disabilities navigate complex content" },
    { word: "ERROR", fact: "Error identification and suggestions improve usability for all users" },
    { word: "IMAGE", fact: "Accessible images provide descriptive alt text for users who can't see the image" },
    { word: "TIMER", fact: "Adjustable timers give users enough time to complete tasks" },
    { word: "MOUSE", fact: "Ensure all functionalities are accessible without a mouse" },
    { word: "FRAME", fact: "Accessible frames contain proper titles and labels for clarity" },
    { word: "VOICE", fact: "Voice recognition software helps users navigate content hands-free" },
    { word: "TOUCH", fact: "Touch-friendly interfaces improve accessibility on mobile devices" },
    { word: "STEPS", fact: "Provide clear steps in multi-step processes for better usability" },
    { word: "PRESS", fact: "Pressable elements should be large and clear for all users" },
    { word: "ROLES", fact: "ARIA roles help screen readers interpret and present page content correctly" },
    { word: "ALIGN", fact: "Proper alignment of elements ensures a readable and structured layout" },
    { word: "PROMO", fact: "Accessible promotional content uses clear text and media alternatives" },
    { word: "CLOSE", fact: "Ensure users can easily close pop-ups and modal dialogs" },
    { word: "TABLE", fact: "Accessible tables use headers to associate data with meaning" },
    { word: "CLICK", fact: "Clickable areas should be large enough for users with limited precision" },
    { word: "SOUND", fact: "Provide volume controls for audio content to assist users with hearing impairments" },
    { word: "VIDEO", fact: "Accessible video includes captions, transcripts, and audio descriptions" },
    { word: "GLARE", fact: "Reduce glare by offering dark mode or high-contrast settings" }
];
